### ISSUE TITLE
When a date set is set as a property all other dates should not be disabled

### ISSUE THREAD

**Issue by camwest** [orion-ui/orion#164]
Please walk through the following steps for reporting an issue about Orion:

## Short description of your issue:

When a date is set as a property it disables all date selections in the date picker. See source code example: https://gomix.com/#!/project/puffy-feather

## How do we reproduce the issue?

Please post a public URL and ideally post a reduced test case. E.g. on jsbin.com that exhibits only your issue and nothing else.

1. Create a moment object
2. Set is as the date object
3. Try selecting another date

Expected: I should be able to select other dates and get change events even if the date property is specified.

## What browsers are affected?

All browsers

## Which Orion version is affected?

N/A

Blocks #77

**Comment by aneyzberg** [comment]
@camwest So looking into this - the current default implementation of the `datepicker` is that dates that are in the past are disabled. The date that you used in your example is prior to today's date, which is why all the other dates were disabled. If you select a day after today's date, all other dates should no longer be disabled. 

If you wish to enable dates in the past, the `isEnabled` function (which validates whether or not a date should be disabled) - should be set to undefined.  This will allow all other dates in the past to be enabled.

**Comment by camwest** [comment]
omg embarrassing!
